name: jansathi_app
description: "JanSathi Voice-First Rural Assistant"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.0
  record: ^5.0.0 # Audio recording
  audioplayers: ^5.0.0 # Audio playback
  path_provider: ^2.1.1 # File storage
  permission_handler: ^11.0.1 # Permissions
  http_parser: ^4.0.2
  connectivity_plus: ^5.0.2 # Network Detection

dev_dependencies:
  flutter_test:
    sdk: flutter
